version: "4.12"

services:
  db:
    image: postgres:14.5
    privileged: true
    ports:
      - "5432:5432"  # проброс портов с внешнего окружения на контейнер
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: DjangoToDo
      POSTGRES_DB: todo
  backend:
    build:
      context: ./todoproject/
    ports:
      - "8080:8080"
    command: bash -c "python manage.py migrate
      && python manage.py mysuper
      && python manage.py users
      && python manage.py fill_data
      && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

