# Generated by Django 4.1.1 on 2022-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_alter_project_url_alter_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("o", "open"), ("c", "closed")], default="o", max_length=1
            ),
        ),
    ]
